# Generated by Django 5.2.2 on 2025-06-08 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashflow",
            options={
                "ordering": ("-date", "-created_at"),
                "verbose_name": "ДДС запись",
                "verbose_name_plural": "ДДС записи",
            },
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="сумма, ₽"),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="дата операции"
            ),
        ),
    ]
